### ISSUE TITLE
Error when querying http://dbpedia.org/sparql

### ISSUE THREAD

**Issue by ablaette** [PolMine/dbpedia#20]
In the other examples, we use the German endpoint http://de.dbpedia.org/sparql . Trying to develop an English example, I get an error from the English SPARQL endpoint.

```r
library(dbpedia)
library(quanteda)
library(dplyr)

options(dbpedia.lang = "en")
options(dbpedia.endpoint = "http://api.dbpedia-spotlight.org/en/annotate")

uritab <- data_char_ukimmig2010 |>
  corpus() |>
  get_dbpedia_uris() %>% 
  add_wikidata_uris(endpoint = "x", progress = TRUE) %>% 
  wikidata_query(id = "P31")
```

Opening and ending tag mismatch: hr line 5 and body
Opening and ending tag mismatch: body line 3 and html
Premature end of data in tag html line 1
Error: 1: Opening and ending tag mismatch: hr line 5 and body
2: Opening and ending tag mismatch: body line 3 and html
3: Premature end of data in tag html line 1

Internally, the error results from this line of the `SPARQL::SPARQL()` function:

```r
tf <- do.call(
getURL, append(list(url = paste(url, "?", param, "=", gsub("\\+", "%2B", URLencode(query,  reserved = TRUE)), extrastr, sep = ""), httpheader = c(Accept = "application/sparql-results+xml")), 
curl_args))
```

**Comment by ablaette** [comment]
It still does not work. Anyway, we got the wrong endpoint and the limit of 100 was too high. This works (without getting wikidata_ids):

```r
library(dbpedia)
library(quanteda)
library(dplyr)

options(dbpedia.lang = "en")
options(dbpedia.endpoint = "http://api.dbpedia-spotlight.org/en/annotate")

httr::set_config(httr::config(ssl_verifypeer = 0L))

uritab <- data_char_ukimmig2010 |>
  corpus() |>
  get_dbpedia_uris() %>% 
  add_wikidata_uris(endpoint = "https://query.wikidata.org/sparql", progress = TRUE, limit = 50) %>% 
  wikidata_query(id = "P31")
```

**Comment by ablaette** [comment]
Maybe queries need to be formulated differently for the other endpoint? This yields zero results:

```r
query <- 'SELECT distinct ?item ?wikidata_uri ?key
WHERE {
  VALUES ?item {<http://dbpedia.org/resource/British_National_Party>}
  ?item owl:sameAs ?wikidata_uri
  FILTER(regex(str(?wikidata_uri), "www.wikidata.org" ) )}
LIMIT 10'

endpoint <- "https://query.wikidata.org/sparql"
sparql_query(endpoint = endpoint, query = query)
```

**Comment by ChristophLeonhardt** [comment]
If you use the DBpedia endpoint (https://dbpedia.org/sparql/) and omit the `?key` variable (which is not used anywhere in the query itself) in your last SPARQL query, you should get the expected result (a Wikidata URI / ID), at least in the interactive DBpedia SPARQL query editor.

### Additional Remarks:

At least in this interactive editor, the inclusion of additional variables such as `?key` leads to an error if they are not used later on. I assume that this also occurs when the endpoint is queried directly. This should be considered when including "optional" variables in the query.

**Comment by ablaette** [comment]
Using the correct endpoint really helps. So this is a working example.

```r
library(dbpedia)
library(quanteda)
library(dplyr)
lib

options(dbpedia.lang = "en")
options(dbpedia.endpoint = "http://api.dbpedia-spotlight.org/en/annotate")

httr::set_config(httr::config(ssl_verifypeer = 0L))

uritab <- data_char_ukimmig2010 |>
  corpus() |>
  get_dbpedia_uris() %>% 
  add_wikidata_uris(endpoint = "https://dbpedia.org/sparql/", progress = TRUE, limit = 50) %>% 
  wikidata_query(id = "P31") %>% 
  as_tibble() %>% 
  filter(grepl("political party", P31))

```
