### ISSUE TITLE
`get_dbpedia_uris()` fails if there are no named entities in the document

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/dbpedia#23]
When processing very short subcorpora (for example paragraphs from GermaParl, see the current example in the README), it is possible that these documents do not contain a single named entity. If named entities are used in the `s_attribute` argument, `get_dbpedia_uris()` will fail in this case because merging potentially retrieved URIs with the empty data.table of non-existing named entities does not work.

**Comment by ablaette** [comment]
I am not sure whether the suggested solution is already complete. I wonder whether columns 'text' and 'ne_type' may be missing later on.

To start with, this is a reproducible example that triggers the errror with the earlier version of dbpedia (v0.1.1.9007):

```r
library(polmineR)
library(dbpedia)

speech <- corpus("GERMAPARL2") %>% 
  subset(protocol_date == "2018-02-22") %>%
  subset(speaker_name == "Angela Merkel") %>%
  subset(p_type == "speech") %>%
  as.speeches(
    s_attribute_name = "speaker_name",
    s_attribute_date = "protocol_date",
    progress = FALSE
  )

no_ne <-  split(speech[[1]], s_attribute = "s")[1:4] %>% merge()

get_dbpedia_uris(x = no_ne, language = "de", s_attribute = "ne_type")
```

**Comment by ablaette** [comment]
The example now works without an irritating warning, if we rely on polmineR v0.8.9.9002. But the return value is `NULL`: Is this the preferred solution? Or should we return an empty `data.table`?

**Comment by ablaette** [comment]
Implemented the empty data.table solution now.
