### ISSUE TITLE
Consider splitting longer text into chunks instead of truncating it

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/dbpedia#46]
Longer documents (approximately over 5600 characters) are currently truncated. That means that one part of the document is not passed to DBpedia Spotlight, i.e. not annotated at all.

Instead of truncating, it should be considered to split the text into chunks if it is too long.

`chunk_text()` of the `tokenizers` R package could facilitate this. In `get_dbpedia_uris()` for `character vectors` this could be implemented along the lines of 

```
if (nchar(x) > max_len) {
  if (verbose) cli_alert_info(
    "input text has length {nchar(x)}, creating chunks of 500 tokens."
  )

  x <- chunk_text(x, chunk_size = 500, lowercase = FALSE, strip_punct = FALSE)
}
```

`x` then becomes a list of character vectors which could be sent to DBpedia Spotlight one by one.

Ideally, the output would still be the entire input document, so it must be taken care when combining the individually returned results from DBpedia Spotlight.

**Comment by ablaette** [comment]
The solution we have implemented starting with v0.1.2.9005 uses overlapping chunks with the maximum length. When combining the results, matches are used that have context to the left and to the right. It should provide better results.
